### ISSUE TITLE
Since yesterday or today, I have been seeing "recommended users".

### ISSUE THREAD

**Issue by beehiveharvest** [shirouzu/Twitter-Stress-Reduction#10]
It is as the title says.

Since yesterday or today, I have been seeing "recommended users".

**Comment by beehiveharvest** [comment]
The symptoms of the bug are as follows 
 
If are not logged in to Twitter, "Recommended Users" is not displayed.

But when log in, "Recommended Users" will be displayed.

**Comment by shirouzu** [comment]
Thank you for your report.
v0.3.3.3 has been released.
