### ISSUE TITLE
❤️などの絵文字に対応

### ISSUE THREAD

**Issue by ME-GA** [shirouzu/Twitter-Stress-Reduction#11]
**機能リクエスト内容**
Twitter上で絵文字として変換される「❤️」「💙」などは除外文字列として
設定しても認識されていないように見受けられます(文字コードなどが変換されるため？(未検証))。
ぜひこれらについても対応していただけると助かります。

**Comment by shirouzu** [comment]
手元で試した範囲だと、ちゃんと効きますね。（Win10 + Chrome最新）
環境によるのですが、Twitter上の絵文字は、しばしば（imgタグによる）画像になります（環境ごとのemojiフォント未対応や絵の不統一を避けるため？）

Chrome等のdevtoolsを使って、当該部分の絵文字の imgタグの alt属性を確認して、絵文字とalt属性文字列を両方とも指定してください。
たとえば 🏳️‍🌈 という emoji は、img タグの alt属性が alt="🏳️‍🌈" となっている場合とalt="レインボーフラッグ" となっている場合があるため、??(レインボーフラッグ|🏳️‍🌈) と指定する必要があります。

**Comment by ME-GA** [comment]
確認が遅くなってしまい、申し訳ありません。

指定した条件としては以下のようなAND条件であり、
最近別のキーワード(絵文字ではなく文字列)を指定したところ
同じように除外ができない状態でした。

==============================
・条件：「❤️」かつ「💙」を含む

・設定

`??^(?=.*❤️)(?=.*💙).*$`

==============================

そのため、絵文字が認識できないというよりは
上記のような肯定先読みの正規表現が認識されていない可能性がありました。
（正規表現が正しいことはチェッカーを使って確認しています）

**Comment by shirouzu** [comment]
「かつ」指定だと、一つのツイートの中に ❤️ と 💙 を含まないと除外されません。
（あと前に書いた通り、絵文字以外に alt属性も指定する必要があります）
まずは、一つの絵文字を使って、単純なパターンから検証してみてください。

**Comment by ME-GA** [comment]
いくつか検証してみましたが、文字・絵文字にかかわらず
以下のように指定の仕方でミュート可否が決まるように見受けられました。

- ミュートされる
```
??.*❤️
??.*キーワード1.*
```

- ミュートされない
```
??.*❤️.*💙
??^(?=.*キーワード1)(?=.*キーワード2).*$
```

**Comment by shirouzu** [comment]
一つのツイートと言っても、絵文字などは span や img で分断していて、一連の文字列として評価できないことが多いので、??(❤️|💙|❤️のALT文字列|💙のALT文字列）などのように記述したほうが良いかも。
いずれにせよ、JS の RegExp(, "u").match() でマッチ評価してるので、絵文字対応してないという話はないはず。

**Comment by ME-GA** [comment]
「❤️」や「💙」の絵文字等はALTの文字列を指定していなくても単独でキーワードとして指定したり、
ご提示いただいたように「??(❤️|💙)」のようなOR条件であれば正常にミュートされました。

ですが、上記のミュートされない例として挙げたようにAND条件として指定した場合に
正常にミュートされない挙動となっているようです。

**Comment by shirouzu** [comment]
ですので、絵文字等が入ると（一つのツイートが）span や imgタグで分断されるために、ひと続きの文字列として評価できない、と書いているのですが…一度、Twitter の 生のHTMLを眺めてみれば意味が少しは判るかもしれません。（返信不要です）

**Comment by k-kuruma** [comment]
横からすみません。kurumaと申します。自分も複数絵文字をフィルターしようとして苦労していました。

ソースコードやXのhtml構造など、少し見てみました。
現状、Xのページ構造自体が、1件のツイートについて、文字列はspan、絵文字は一文字ずつimgに別れており、span一件ごと、img一件ごとに条件チェックを行う動作になっている、ようですね。

手元にて、tw_promo_check()の構造を少しいじってみたところ、少なくとも数件についてはうまく動くようでした。
- tw_promo_check() でdocument.querySelectorAll() にて、spanとa、divとimgを検索している箇所を、マージする。(内部でe.tagNameで分岐すれば今まで通りの処理のままマージできる)
- 1件のツイートについて、文字列とimgのaltの内容を結合する文字列を作成する。ループ先頭で空文字列とし、spanとimgのaltを検出するごとに、追加していく。ついでに、spanまたはimgの「htmlノード」を最後の一件だけ覚えておく。
- document.querySelectorAll() にて検索する対象にarticleを追加する。どうやらこれが1件のツイートに1タグのようなので、articleを検出したとき、前の1件のツイートについて、tw_purge_func()を呼び出す。この際、マージしたテキストと覚えておいたhtmlノードを使う。
- ループが終わった時点で最後の1件のツイートが未処理なので、その1件を同様にtw_purge_func()でチェックする。

手元で試したところ、こうすると「絵文字が2文字連続していたら」などの条件もマッチできる、ようです。ただし、最初の数件はなんとなくうまく行くのですが、件数が多くなってくるとうまく働かなくなってしまいます。
もうすこし調べてみます。

**Comment by k-kuruma** [comment]
> もうすこし調べてみます。

の件、調べたので書いておきます。蛇足に蛇足でお目汚しすみません。

tw_update_purge_func() にて tw_purge_func (NGワードチェック処理) の中身を定義しています。この中で、
str.length >= tw_maxname_len
と比較している箇所があり、意味としては

「300(バイト？文字？)以上の文字列が判定に渡ってきた場合は（設定画面で指定したNGワードにかかわらず）チェック通過」

と解釈しました。この判定をコメントアウトしたところ、謎のすり抜け現象がなくなったようです。

私が先のコメントに書いた改造は、1ツイートの文字列を結合していき、完成したら一気にチェック処理に渡す、という話ですが、そうすると引用ツイートなども結合され、長文になって、本コメント記載の判定で 通過 と判定されていたようです。

ご参考情報でした。
