### ISSUE TITLE
サポート切れ予定に対するアップデート対応を行ってほしい

### ISSUE THREAD

**Issue by toppa0911** [shirouzu/Twitter-Stress-Reduction#12]
**機能リクエスト内容**
いつも利用させて頂いています。
「この拡張機能は、Chrome 拡張機能のベスト プラクティスに沿わないため、まもなくサポートされなくなる可能性があります」
という表示がChromeウェブストアに表示されています。Manifest V3への対応が出来ていないかも知れないですが、
対応していただくことはできないでしょうか。

**Comment by shirouzu** [comment]
Manifest V3の話ですね…困ったものです。
