### ISSUE TITLE
ショートカットキー無効化の機能について

### ISSUE THREAD

**Issue by tekkkos10** [shirouzu/Twitter-Stress-Reduction#2]
アドオン、大変便利に使わせていただいております。
報告なのですが、「ショートカットキー無効化」の機能が動作していないようです。
（いいねが押せてしまったり、ユーザーをブロックするか問う画面が表示されたりする）
他に入れているアドオンを無効にして単体にしても動かないようです。
バージョンはver 0.2.9.5、ブラウザはFirefox 96.0(64bit)です。
もし解決する方法がありましたらご教示頂けると嬉しいです。

設定は以下のようにしてあります。非表示文字列は空欄です。
![スクリーンショット 2022-01-13 191126](https://user-images.githubusercontent.com/79202164/149311206-ac7f96d8-1cf1-4a07-98f4-b6f60a15ca1b.png)

**Comment by FastCopyLab** [comment]
確認しました。
どうも、いろいろとショートカットキーが変更されてるみたいですね。
（いいねが F → L など）
最新に追随した v3.0.0 をリリースしておきました。

**Comment by tekkkos10** [comment]
更新後、無効化できました！
今後も使わせて頂きます、本当にありがとうございました！
