### ISSUE TITLE
ブックマークサイドバーが出せなくなる

### ISSUE THREAD

**Issue by xenyou** [shirouzu/Twitter-Stress-Reduction#3]
**エラー内容**
ブックマークサイドバーが出せなくなる。

**再現方法**
本add-onを有効にしてtwitter.comにログインする。するとcommand+bで出せるはずのブックマークサイドバーが出ない。

**バージョン・環境**
 - Browser種類 firefox 96.0.3 
 - OSバージョン macOS 12.2

**Comment by shirouzu** [comment]
設定にある「ショートカットを無効化する」を外してみて下さい。

**Comment by xenyou** [comment]
素早い回答ありがとうございます。
サイドバー出るようになりました。
仕様ということでしたらクローズしていただければと思います。

**Comment by shirouzu** [comment]
次のバージョンから、コマンドキーが押されていた場合は、ショートカット無効化から除外するようにしておきますね。
