### ISSUE TITLE
記述例の間違い

### ISSUE THREAD

**Issue by sseiichi** [shirouzu/Twitter-Stress-Reduction#4]
**エラー内容**
オプションの
トレンド等で「非表示化したい検索文字列」
欄に、

（記述例）に書かれている
?(ORICON NEWS|BLOGOS|Business Insider|news zero||WWDJAPAN)
をコピペして追記すると

以下のエラーが出ます。
 match exists like (|...), (...||...), or (...|)

**再現方法**
同上

**バージョン・環境**
 - Firefox 100.0.2
 - Windows 10

**スクリーンショット**
なし

**Comment by shirouzu** [comment]
ご報告ありがとうございます。
次のバージョンで修正しておきます。
