### ISSUE TITLE
「さらに表示」というリコメンドを消す方法

### ISSUE THREAD

**Issue by sseiichi** [shirouzu/Twitter-Stress-Reduction#5]
**質問**
「さらに表示」というリコメンドを消したいです。

オプションの
トレンド等で「非表示化したい検索文字列」に
「さらに表示」
を追加しても、表示されます。

**備考**
![rapture_20220527232842](https://user-images.githubusercontent.com/493035/170719830-e3196838-52cd-4e45-b152-e0f56f97c5af.png)

**Comment by shirouzu** [comment]
これは本文という扱いに近いので、
??^(さらに表示)$
で消えると思います。

**Comment by sseiichi** [comment]
ご回答ありがとうございます。

さっそく試してみようと思ったのですが、
Twitterの仕様が変更されたのか、
Twitter Stress Reductionをインストールしていないブラウザで閲覧しても、
当該リコメンドは既に全く表示されなくなっていました。

教えていただいた記述で、
本文を非表示にできることは確認できました。

ともかく教えていただきありがとうございました。
