### ISSUE TITLE
「ショートカットキーの無効化」で無効化されないキーがある

### ISSUE THREAD

**Issue by petoronchino** [shirouzu/Twitter-Stress-Reduction#6]
初めまして。質問させてください。

「ショートカットキーの無効化」ですが、無効化されないキーがあります。
（次のツイートを選択する「J」キーや、前のツイートを選択する「K」キー等）
全ショートカットキーを無効化したいのですが、どうすればよろしいでしょうか。

よろしくお願いいたします。

**Comment by shirouzu** [comment]
現状は「いいね」や「ミュート」「ブロック」などの影響が大きい物を選んで無効化しています。
ご了承下さい。
![image](https://user-images.githubusercontent.com/1759911/170857662-2b90d892-b0e0-4ef4-9bb2-824588730f5f.png)

**Comment by petoronchino** [comment]
ありがとうございます。
そうだったのですね、わかりました！

**Comment by shirouzu** [comment]
仕様を変更して、A-Z の全てのキーを無効化するようにしておきました。(v3.0.12)

**Comment by petoronchino** [comment]
ありがとうございます、助かります！
