### ISSUE TITLE
リストのアイコン下に「〇」が表示される

### ISSUE THREAD

**Issue by petoronchino** [shirouzu/Twitter-Stress-Reduction#7]
報告させてください。

リストのアイコン下にですが、「〇」が表示されます。
画像折り畳みボタンが表示されてしまっているのではないか、と思います。
対応をよろしくお願いいたします。

備考画像
![image](https://user-images.githubusercontent.com/106461665/170854011-dbb543a2-a01a-4b23-b394-f09685994a88.png)

**Comment by shirouzu** [comment]
ご報告ありがとうございます。
これはリスト選択ボタン（主にモバイル用）なのですが、Twitter側のコード変更で下に出るようになってしまってますね。
次のバージョンで何らかの対処を入れておきます。

**Comment by petoronchino** [comment]
ありがとうございます。
そうだったのですね。
次バージョン楽しみにしています！
