### ISSUE TITLE
絵文字を含む検索文字列が機能しない

### ISSUE THREAD

**Issue by timarupopoka** [shirouzu/Twitter-Stress-Reduction#8]
**エラー内容**
絵文字を含む検索文字列が機能しません。

**再現方法**
本文に`500🅿️`を含むツイートを非表示にしたいのですが
`??.*🅿️.*`
`??.*500🅿️.*`
前者の書き方では消えてくれますが後者は機能しません。
最終的には以下のように使いたいです。
`??.*\d+🅿️.*`

**バージョン・環境**
 - Browser種類
 Firefox 110.0.1 (64 ビット)
 - OSバージョン
Windows 10 Home 22H2 19045.2604

よろしくおねがいします。

**Comment by shirouzu** [comment]
これ、いまのところ対応はちょっと面倒なので保留とします。
詳細を書いておくと、Twitter入力時は 500🅿️ という連続文字列ですが、Twitter表示時には 🅿️ だけ画像として切り出されて、`<span>500</span><img alt="🅿️"></img>`という形に分離しているためです。
